import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProfileUI from "@/components/profile-ui";
import { ThemeProvider } from "@/components/theme-provvider";
import { ModeToggle } from "@/components/mode-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-wrap items-end content-end justify-end">
            <ModeToggle />
          </div>
          <div className="h-[100dvh] flex items-center content-center ml-2">
            <ProfileUI />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
