import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProfileUI from "@/components/profile-ui";
import { Card1 } from "@/components/card1";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Card1 />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
